name: Feature Request
description: Propose a student-focused improvement.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: dropdown
    id: project
    attributes:
      label: Related project
      options:
        - Repository-wide / multiple projects
        - automl-hpo-showcase
        - batch-vs-stream-ml-systems-showcase
        - causalml-kaggle-showcase
        - credit-risk-classification-capstone-showcase
        - demand-api-observability-showcase
        - eda-leakage-profiling-showcase
        - feature-engineering-dimred-showcase
        - learning-to-rank-foundations-showcase
        - mlops-drift-production-showcase
        - model-release-rollout-showcase
        - nyc-demand-forecasting-foundations-showcase
        - ranking-api-productization-showcase
        - rl-bandits-policy-showcase
        - sota-supervised-learning-showcase
        - sota-unsupervised-semisup-showcase
        - xai-fairness-audit-showcase
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Documentation
        - Notebooks
        - Scripts
        - Tests
        - CI
        - New showcase project
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What student pain point does this fix?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
    validations:
      required: true
  - type: textarea
    id: success
    attributes:
      label: How to measure success
