name: Learning Question
description: Ask a concept or interpretation question.
title: "[Learning]: "
labels: ["question", "learning"]
body:
  - type: dropdown
    id: project
    attributes:
      label: Project
      options:
        - automl-hpo-showcase
        - batch-vs-stream-ml-systems-showcase
        - causalml-kaggle-showcase
        - credit-risk-classification-capstone-showcase
        - demand-api-observability-showcase
        - eda-leakage-profiling-showcase
        - feature-engineering-dimred-showcase
        - learning-to-rank-foundations-showcase
        - mlops-drift-production-showcase
        - model-release-rollout-showcase
        - nyc-demand-forecasting-foundations-showcase
        - ranking-api-productization-showcase
        - rl-bandits-policy-showcase
        - sota-supervised-learning-showcase
        - sota-unsupervised-semisup-showcase
        - xai-fairness-audit-showcase
    validations:
      required: true
  - type: input
    id: command
    attributes:
      label: Command run (optional)
      description: Include the command you ran before the question came up.
      placeholder: make run
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: What concept or output is unclear?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context and artifact
      description: Include the command, notebook section, or artifact path and what you expected.
  - type: textarea
    id: tried
    attributes:
      label: What you already tried
